# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3c2f4b9db588fdcf650ff589a7bc2dfe7ee046c2ef2a096429c6fe54eab32cea3f78f87990fa7339b565376a490ed47aa26d0844ce4c18c03f41b7b9cc1659

test:
  secret_key_base: 46f9d667a1ddff7bb8d4b5e5a6d5fff3a79149b1744c474da4c985a4f2232a3cc5cc2ebcedc3d865accdebca783bea1b6f77b7226eaf339fdc6f63f44640e84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
